version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: phdict_postgres
    restart: always
    environment:
      POSTGRES_USER: phdict
      POSTGRES_PASSWORD: phdict
      POSTGRES_DB: phdict_dev
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
